name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours
  workflow_dispatch:          # lets you run it manually from the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
         outputs: |
               dist/snake-light.svg?palette=github-light&color_snake=16A34A&color_dots=#ebedf0,#BBF7D0,#86EFAC,#4ADE80,#16A34A
               dist/snake-dark.svg?palette=github-dark&color_snake=22C55E&color_dots=#2d3343,#14532D,#166534,#16A34A,#22C55E
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animation [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
